version: "3"

vars:
  APP_NAME: goact-stack
  DEV_IMAGE: "{{.APP_NAME}}:dev"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  # =============================================================================
  # Development (Docker-based)
  # =============================================================================

  dev:
    desc: Start development environment with hot-reload
    cmds:
      - docker compose up --build

  dev-stop:
    desc: Stop development environment
    cmds:
      - docker compose down

  dev-logs:
    desc: View development logs
    cmds:
      - docker compose logs -f

  dev-shell:
    desc: Open shell in dev container
    cmds:
      - docker compose exec dev sh

  # =============================================================================
  # Build & Release (via Dagger)
  # =============================================================================

  build:
    desc: Build production container via Dagger
    cmds:
      - dagger -m .dagger call release --source=.

  build-frontend:
    desc: Build frontend assets via Dagger
    cmds:
      - dagger -m .dagger call build-frontend --source=.

  # =============================================================================
  # Testing & Linting (via Dagger)
  # =============================================================================

  test:
    desc: Run Go tests via Dagger
    cmds:
      - dagger -m .dagger call test --source=.

  lint:
    desc: Run Go linter via Dagger
    cmds:
      - dagger -m .dagger call lint --source=.

  lint-frontend:
    desc: Run frontend ESLint via Dagger
    cmds:
      - dagger -m .dagger call lint-frontend --source=.

  typecheck:
    desc: Run TypeScript type-check via Dagger
    cmds:
      - dagger -m .dagger call typecheck --source=.

  check:
    desc: Run all checks (lint, typecheck, test)
    cmds:
      - task: lint
      - task: lint-frontend
      - task: typecheck
      - task: test

  # =============================================================================
  # Formatting (via Dagger)
  # =============================================================================

  fmt:
    desc: Format Go code via Dagger
    cmds:
      - dagger -m .dagger call fmt --source=. export --path=.

  fmt-frontend:
    desc: Format frontend code via Dagger
    cmds:
      - dagger -m .dagger call fmt-frontend --source=. export --path=.

  # =============================================================================
  # Cleanup
  # =============================================================================

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf ./tmp ./bin
      - rm -rf ./frontend/node_modules
      - rm -rf ./internal/static/dist

  clean-docker:
    desc: Remove Docker volumes and images
    cmds:
      - docker compose down -v
      - docker rmi {{.DEV_IMAGE}} 2>/dev/null || true
